# Generated by Django 3.0.8 on 2020-12-22 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='feedback_count',
        ),
        migrations.AddField(
            model_name='song',
            name='feedback_count',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
