# Generated by Django 3.0.8 on 2020-12-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20201222_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='feedback_count',
            new_name='votes',
        ),
    ]
