# Generated by Django 3.0.8 on 2020-12-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20201222_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
